dist: xenial
sudo: false
language: python
python:
  - "3.11"
  - "3.12"

services:
   - mongodb

before_install:
  - pip install pycodestyle
install:
  - mongo --version
  - pip install --upgrade pip
  - pip install python-dateutil --upgrade
  - pip install pytz --upgrade
  - pip install tzlocal --upgrade
  - pip install pymongo --upgrade
  - pip install numpy --upgrade
  - pip install pandas --upgrade
  - pip install decorator --upgrade
  - pip install enum34 --upgrade
  - pip install lz4 --upgrade
  - pip install mock --upgrade
  - pip install mockextras
  - pip install pytest --upgrade
  - pip install pytest-cov --upgrade
  - pip install pytest-server-fixtures --upgrade
  - pip install pytest-timeout --upgrade
  - pip install pytest-xdist --upgrade
  - pip install setuptools-git --upgrade
script:

